### ISSUE TITLE
pythonDir variable seems to make error

### ISSUE THREAD

**Issue by Askhento** [shmulvad/alfred-tinypng#1]
For some reason my python is python2.7, but you are using f string syntax which cause an error:

<img width="669" alt="Screenshot 2020-12-02 at 14 47 59" src="https://user-images.githubusercontent.com/34323808/100856993-ecb1e480-34ad-11eb-8c95-ebff967a6179.png">

Changing to python3 fixed the issue. Maybe need to be explicit here, not sure.

**Comment by shmulvad** [comment]
Thanks. I have no plans to add support for Python 2.7, but I have now in db20fa8ea2fcfe334d4013dc2e2773b448fcc356 explicitly mentioned in the README and Alfred description that changing the Python path might be needed.
