### ISSUE TITLE
The workflow doesn't seem to work

### ISSUE THREAD

**Issue by jerryyang0611** [shmulvad/alfred-tinypng#3]
Hi, I think I encountered the exact same issues with [this](https://github.com/shmulvad/alfred-tinypng/issues/2#issue-776782326). After typing the trigger keyword, Alfred tends to search it in google instead of activating the workflow. 

The debug mode error is:
![image](https://user-images.githubusercontent.com/45359868/118734648-bfc47480-b836-11eb-98d2-20c564b6fb98.png)

I'm pretty sure I've got Python version at like 3.7 or above, so I think the version issue is not the case for me. Pls send help if you got time. THX!

**Comment by shmulvad** [comment]
Hi, can you give me more info on your Alfred version, Python version, operating system and anything else that might be useful?

**Comment by shmulvad** [comment]
The bug in #2 is that the user does not have Anaconda installed, thus there is an error with the path. With future versions of the script, I've changed the default path of the user's Python installation to `/usr/bin/python3`. What happens if you type `/usr/bin/python3 --version` in a terminal?

**Comment by jerryyang0611** [comment]
I've sorted out, thx for pointing me to the #2. I forgot to put the python variable 😄
