### ISSUE TITLE
Problem with apple system events

### ISSUE THREAD

**Issue by Markhenn** [shmulvad/alfred-tinypng#4]
Hello, 

thank you for the great workflow, but I am still experiencing a problem with the System Events. I did set the python3 path and my own API key. But when I start the workflow  it breaks down with the following error: `getPath.scpt: execution error: Not authorized to send Apple events to System Events. (-1743)`

I am using an M1 Pro MacBook macOS Monterey. Homebrew is now installing python3 in to `/opt/homebrew/bin/python3` but that seems to work. 

Maybe you have an idea what the problem could be. Thank you!

I add the full error description below. 

![Set up](https://user-images.githubusercontent.com/26623749/146367114-1e59aa21-96ac-46c5-bc0d-eb2c110ebc66.png)
![Error log](https://user-images.githubusercontent.com/26623749/146367122-37e145e0-49b4-485a-8829-52ac0ecae02f.png)

**Comment by shmulvad** [comment]
The original error occurs at `getPath.scpt: execution error: Not authorized to send Apple events to System events`, which causes further errors down the line. This seems to be some security/authorization error.

Can you try the proposed solution mentioned here and see if it solves your problem? https://stackoverflow.com/a/51847089

**Comment by Markhenn** [comment]
Thank you that solved it! I was going through the Privacy setting before, but missed it there in automation. Or maybe it was added after I restarted the computer yesterday. When I just looked at it again it was the only check mark that was blank.
